### ISSUE TITLE
Panic from unwrapping `None`

### ISSUE THREAD

**Issue by segeljakt** [gwierzchowski/csv-async#22]
Hi, this library works great overall but after running it for a few minutes I get a panic.

This is the stacktrace:

```rust
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value',
/Users/klasseg/.cargo/registry/src/github.com-1ecc6299db9ec823/csv-async-1.2.6/src/async_readers/mod.rs:1479:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/panicking.rs:114:5
   3: <&mut S as futures_core::stream::Stream>::poll_next
   4: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
   5: std::thread::local::LocalKey<T>::with
   6: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   7: tokio::runtime::scheduler::current_thread::Context::enter
   8: tokio::macros::scoped_tls::ScopedKey<T>::set
   9: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  10: tokio::runtime::runtime::Runtime::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'Failed to join thread: Any { .. }', dataflow/src/runtime.rs:56:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/result.rs:1750:5
   3: <dataflow::runtime::Runtime as core::ops::drop::Drop>::drop
   4: local_single_thread_debug::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm using this deserializer:
```rust
let rx = File::open(path).await.expect("Failed to open file");
let mut rx = csv_async::AsyncReaderBuilder::new()
    .has_headers(false)
    .create_deserializer(rx);
```
and calling `rx.next()`.

**Comment by gwierzchowski** [comment]
If you're using `create_deserializer`, then you pretend to use `serde` and serialize  to some existing structure.
And therefore you should call `into_deserialize` with your structure hint before calling `next`, example:
https://docs.rs/csv-async/latest/csv_async/struct.AsyncReaderBuilder.html#method.create_deserializer
Calling `next` on object returned from  `create_deserializer` should not compile giving error: `method cannot be called on 'AsyncDeserializer<tokio::fs::File>' due to unsatisfied trait bounds`.

If you do not want `serde` and need more flexible record set, then use `create_reader` and `into_records` instead.

I did not managed to get above panic, neither with empty cvs file or any other.
If you call  `into_deserialize` and still getting panic - please send me an minimal build-able example with input csv file.

**Comment by segeljakt** [comment]
@gwierzchowski Hi again, I tried using `into_deserialize` but get the same problem. This is the code:

## `src/main.rs`
```rust
use serde::Deserialize;
use serde::Serialize;
use tokio::fs::File;
use tokio_stream::StreamExt;

#[derive(Serialize, Deserialize, Debug)]
struct Order {
    name: String,
    price: i32,
    time: String,
}

#[tokio::main]
async fn main() {
    let file = File::open("orders.csv").await.expect("Failed to open file");
    let mut rx = csv_async::AsyncReaderBuilder::new()
        .has_headers(false)
        .create_deserializer(file)
        .into_deserialize::<Order>();
    loop {
        if let Some(Ok(order)) = rx.next().await {
            println!("{:?}", order);
        }
    }
}
```
## `Cargo.toml`
```toml
[package]
name = "csv-async-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.24.2", features = ["full", "tracing"] }
tokio-stream = { version = "0.1.11" }
csv-async = { version = "1.2.6", features = ["with_serde", "tokio"] }
serde = { version = "1.0.152", features = ["derive", "rc"] }
```

## `orders.csv`
```csv
spaghetti,139,2023-04-18T12:15:00Z
soup,109,2023-04-18T12:16:10Z
pancakes,99,2023-04-18T12:17:20Z
pizza,129,2023-04-18T12:18:30Z
sandwich,79,2023-04-18T12:19:40Z
tacos,149,2023-04-18T12:20:50Z
burger,109,2023-04-18T12:22:00Z
sushi,179,2023-04-18T12:23:10Z
salad,89,2023-04-18T12:24:20Z
steak,199,2023-04-18T12:25:30Z
```
## Output:
```
csv-async-test ❯ cargo r
   Compiling csv-async-test v0.1.0 (/Users/klasseg/Workspace/rust/csv-async-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running `target/debug/csv-async-test`
Order { name: "spaghetti", price: 139, time: "2023-04-18T12:15:00Z" }
Order { name: "soup", price: 109, time: "2023-04-18T12:16:10Z" }
Order { name: "pancakes", price: 99, time: "2023-04-18T12:17:20Z" }
Order { name: "pizza", price: 129, time: "2023-04-18T12:18:30Z" }
Order { name: "sandwich", price: 79, time: "2023-04-18T12:19:40Z" }
Order { name: "tacos", price: 149, time: "2023-04-18T12:20:50Z" }
Order { name: "burger", price: 109, time: "2023-04-18T12:22:00Z" }
Order { name: "sushi", price: 179, time: "2023-04-18T12:23:10Z" }
Order { name: "salad", price: 89, time: "2023-04-18T12:24:20Z" }
Order { name: "steak", price: 199, time: "2023-04-18T12:25:30Z" }
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/klasseg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/csv-async-1.2.6/src/async_readers/mod.rs:1737:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The panic seems to happen when calling `next()` after it has previously returned `None`. In my case I am interested in parsing infinite streams of CSV. I would like the reader to wait until new CSV lines are appended to the file. Is this possible?

**Comment by segeljakt** [comment]
## Output:
```
csv-async-test ❯ cargo r
   Compiling csv-async-test v0.1.0 (/Users/klasseg/Workspace/rust/csv-async-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running `target/debug/csv-async-test`
Order { name: "spaghetti", price: 139, time: "2023-04-18T12:15:00Z" }
Order { name: "soup", price: 109, time: "2023-04-18T12:16:10Z" }
Order { name: "pancakes", price: 99, time: "2023-04-18T12:17:20Z" }
Order { name: "pizza", price: 129, time: "2023-04-18T12:18:30Z" }
Order { name: "sandwich", price: 79, time: "2023-04-18T12:19:40Z" }
Order { name: "tacos", price: 149, time: "2023-04-18T12:20:50Z" }
Order { name: "burger", price: 109, time: "2023-04-18T12:22:00Z" }
Order { name: "sushi", price: 179, time: "2023-04-18T12:23:10Z" }
Order { name: "salad", price: 89, time: "2023-04-18T12:24:20Z" }
Order { name: "steak", price: 199, time: "2023-04-18T12:25:30Z" }
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/klasseg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/csv-async-1.2.6/src/async_readers/mod.rs:1737:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by segeljakt** [comment]
I think the panic seems to happen when calling `next()` after it has previously returned `None`.

**Comment by gwierzchowski** [comment]
@segeljakt I have pushed commit which should fix panic. Reader will return None all the time after reaching end of file - in similar way that sync csv does.. Described by you infinite stream is little beyond goals of such libraries like this. But such custom deserializer it could be implemented easily by compositing with this lib one and observing file modification date - if it changes file could be reopened and re-winded to last read position (using seek() available in reader interface).
